In [13]:
import pandas as pd
import numpy as np
import pprint
%matplotlib inline
%precision 3
np.set_printoptions(precision=3)



In [2]:
head = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
house = pd.read_csv('housing.csv',delim_whitespace=True, names=head)

In [3]:
house.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [4]:
house.shape

(506, 14)

In [5]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(house)
print (X_std[0:14])
print ("The shape of Feature Matrix is -",X_std.shape)

[[-0.42   0.285 -1.288 -0.273 -0.144  0.414 -0.12   0.14  -0.983 -0.667
  -1.459  0.441 -1.076  0.16 ]
 [-0.417 -0.488 -0.593 -0.273 -0.74   0.194  0.367  0.557 -0.868 -0.987
  -0.303  0.441 -0.492 -0.102]
 [-0.417 -0.488 -0.593 -0.273 -0.74   1.283 -0.266  0.557 -0.868 -0.987
  -0.303  0.396 -1.209  1.324]
 [-0.417 -0.488 -1.307 -0.273 -0.835  1.016 -0.81   1.078 -0.753 -1.106
   0.113  0.416 -1.362  1.183]
 [-0.412 -0.488 -1.307 -0.273 -0.835  1.229 -0.511  1.078 -0.753 -1.106
   0.113  0.441 -1.027  1.488]
 [-0.417 -0.488 -1.307 -0.273 -0.835  0.207 -0.351  1.078 -0.753 -1.106
   0.113  0.411 -1.043  0.671]
 [-0.41   0.049 -0.477 -0.273 -0.265 -0.388 -0.07   0.839 -0.523 -0.578
  -1.505  0.427 -0.031  0.04 ]
 [-0.404  0.049 -0.477 -0.273 -0.265 -0.16   0.979  1.025 -0.523 -0.578
  -1.505  0.441  0.911  0.497]
 [-0.396  0.049 -0.477 -0.273 -0.265 -0.931  1.117  1.087 -0.523 -0.578
  -1.505  0.328  2.422 -0.657]
 [-0.401  0.049 -0.477 -0.273 -0.265 -0.4    0.616  1.33  -0.523 -0.578
 

C:\Users\pc\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\pc\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [6]:
X_covariance_matrix = np.cov(X_std.T)

In [7]:
X_covariance_matrix

array([[ 1.002, -0.201,  0.407, -0.056,  0.422, -0.22 ,  0.353, -0.38 ,
         0.627,  0.584,  0.291, -0.386,  0.457, -0.389],
       [-0.201,  1.002, -0.535, -0.043, -0.518,  0.313, -0.571,  0.666,
        -0.313, -0.315, -0.392,  0.176, -0.414,  0.361],
       [ 0.407, -0.535,  1.002,  0.063,  0.765, -0.392,  0.646, -0.709,
         0.596,  0.722,  0.384, -0.358,  0.605, -0.485],
       [-0.056, -0.043,  0.063,  1.002,  0.091,  0.091,  0.087, -0.099,
        -0.007, -0.036, -0.122,  0.049, -0.054,  0.176],
       [ 0.422, -0.518,  0.765,  0.091,  1.002, -0.303,  0.733, -0.771,
         0.613,  0.669,  0.189, -0.381,  0.592, -0.428],
       [-0.22 ,  0.313, -0.392,  0.091, -0.303,  1.002, -0.241,  0.206,
        -0.21 , -0.293, -0.356,  0.128, -0.615,  0.697],
       [ 0.353, -0.571,  0.646,  0.087,  0.733, -0.241,  1.002, -0.749,
         0.457,  0.507,  0.262, -0.274,  0.604, -0.378],
       [-0.38 ,  0.666, -0.709, -0.099, -0.771,  0.206, -0.749,  1.002,
        -0.496, -0.535, -

In [8]:
eig_vals, eig_vecs = np.linalg.eig(X_covariance_matrix)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 2.423e-01 -6.587e-02  3.951e-01  1.004e-01  4.958e-03  2.246e-01
   7.771e-01  1.574e-01 -5.911e-02 -9.703e-02 -2.542e-01  7.138e-02
  -6.328e-02 -7.107e-02]
 [-2.454e-01 -1.480e-01  3.945e-01  3.430e-01  1.145e-01  3.357e-01
  -2.742e-01 -3.803e-01  9.630e-02  1.324e-01 -3.829e-01 -2.456e-01
   2.211e-01 -1.277e-01]
 [ 3.319e-01  1.271e-01 -6.608e-02 -9.627e-03 -2.258e-02  8.082e-02
  -3.403e-01  1.717e-01  2.355e-01 -8.372e-02 -6.270e-01  2.548e-01
  -3.484e-01  2.738e-01]
 [-5.027e-03  4.107e-01 -1.253e-01  7.004e-01 -5.352e-01 -1.626e-01
   7.408e-02 -3.293e-02 -2.349e-02  4.992e-02  1.864e-02  4.171e-02
   1.904e-02 -9.968e-03]
 [ 3.252e-01  2.543e-01 -4.648e-02  5.371e-02  1.946e-01  1.490e-01
  -1.981e-01  4.746e-02 -8.765e-02 -5.250e-01  4.302e-02  2.116e-01
   4.491e-01 -4.375e-01]
 [-2.028e-01  4.340e-01  3.534e-01 -2.934e-01 -8.320e-03 -1.311e-01
   7.408e-02 -4.376e-01 -7.191e-03  4.989e-02  3.667e-03  5.261e-01
   1.256e-01  2.240e-01]
 [ 2.970e-01  2.603e

In [9]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort(key=lambda x: x[0], reverse=True)

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
6.558951934253075
1.652798305551123
1.3515770248645802
0.8882953936446625
0.8525843888559502
0.6613177254455688
0.536471019858816
0.4038747537352732
0.27781262058510586
0.2527569590612848
0.2132116163514291
0.18334985084676733
0.13427506228703565
0.060446116936559074


In [10]:
total = sum(eig_vals)
var_exp = [(i / total)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)
print ("Variance captured by each component is \n",var_exp)
print(40 * '-')
print ("Cumulative variance captured as we travel each component \n",cum_var_exp)

Variance captured by each component is 
 [46.75706841894131, 11.782370755269861, 9.635042314463762, 6.332427636794953, 6.077853139077566, 4.714362667278546, 3.8243628603712874, 2.87911844489431, 1.9804541698966462, 1.8018388527096103, 1.51993035371925, 1.307053566877717, 0.9572121182235034, 0.4309047014816816]
----------------------------------------
Cumulative variance captured as we travel each component 
 [ 46.757  58.539  68.174  74.507  80.585  85.299  89.123  92.003  93.983
  95.785  97.305  98.612  99.569 100.   ]


In [11]:
print ("All Eigen Values along with Eigen Vectors")
pprint.pprint(eig_pairs)
print(40 * '-')
matrix_w = np.hstack((eig_pairs[0][1].reshape(14,1),
                      eig_pairs[1][1].reshape(14,1)))

print ('Matrix W:\n', matrix_w)

All Eigen Values along with Eigen Vectors
[(6.558951934253075,
  array([ 0.242, -0.245,  0.332, -0.005,  0.325, -0.203,  0.297, -0.298,
        0.303,  0.324,  0.208, -0.197,  0.311, -0.267])),
 (1.652798305551123,
  array([-0.066, -0.148,  0.127,  0.411,  0.254,  0.434,  0.26 , -0.359,
        0.031,  0.009, -0.315,  0.026, -0.201,  0.445])),
 (1.3515770248645802,
  array([ 3.951e-01,  3.945e-01, -6.608e-02, -1.253e-01, -4.648e-02,
        3.534e-01, -2.008e-01,  1.571e-01,  4.185e-01,  3.432e-01,
        3.991e-04, -3.614e-01, -1.611e-01,  1.632e-01])),
 (0.8882953936446625,
  array([ 0.1  ,  0.343, -0.01 ,  0.7  ,  0.054, -0.293, -0.078,  0.185,
       -0.051, -0.027, -0.342, -0.202,  0.243, -0.18 ])),
 (0.8525843888559502,
  array([ 0.005,  0.114, -0.023, -0.535,  0.195, -0.008,  0.15 , -0.106,
       -0.23 , -0.163, -0.616, -0.367,  0.178, -0.051])),
 (0.6613177254455688,
  array([ 0.225,  0.336,  0.081, -0.163,  0.149, -0.131,  0.061, -0.012,
        0.135,  0.188, -0.279,  0.786

In [12]:
Y = X_std.dot(matrix_w)
print (Y[0:14])

[[-2.087  0.493]
 [-1.373 -0.171]
 [-2.377  0.914]
 [-2.838  0.195]
 [-2.773  0.433]
 [-2.301 -0.329]
 [-1.309 -0.221]
 [-0.929  0.098]
 [ 0.052 -1.043]
 [-0.908 -0.552]
 [-0.644 -0.484]
 [-1.08  -0.403]
 [-1.361 -0.686]
 [-0.62  -0.898]]
